export interface Word {
  word: string;
  translation: string;
}

export const words: Word[] = [
  { word: "Merhaba", translation: "Hello" },
  { word: "Teşekkürler", translation: "Thank you" },
  { word: "Evet", translation: "Yes" },
  { word: "Hayır", translation: "No" },
  { word: "Lütfen", translation: "Please" },
  { word: "Günaydın", translation: "Good morning" },
  { word: "İyi akşamlar", translation: "Good evening" },
  { word: "İyi geceler", translation: "Good night" },
  { word: "Nasılsın?", translation: "How are you?" },
  { word: "Ben iyiyim", translation: "I am fine" },
  { word: "Adın ne?", translation: "What is your name?" },
  { word: "Benim adım...", translation: "My name is..." },
  { word: "Tanıştığımıza memnun oldum", translation: "Nice to meet you" },
  { word: "Hoşçakal", translation: "Goodbye" },
  { word: "Görüşürüz", translation: "See you later" },
  { word: "Afedersiniz", translation: "Excuse me" },
  { word: "Özür dilerim", translation: "I'm sorry" },
  { word: "Anlamıyorum", translation: "I don't understand" },
  { word: "Biliyorum", translation: "I know" },
  { word: "Bilmiyorum", translation: "I don't know" },
  { word: "Yardım", translation: "Help" },
  { word: "Doktor", translation: "Doctor" },
  { word: "Polis", translation: "Police" },
  { word: "Ekmek", translation: "Bread" },
  { word: "Su", translation: "Water" },
  { word: "Yemek", translation: "Food" },
  { word: "Para", translation: "Money" },
  { word: "Banka", translation: "Bank" },
  { word: "Otel", translation: "Hotel" },
  { word: "Restoran", translation: "Restaurant" },
  { word: "Hastane", translation: "Hospital" },
  { word: "Eczane", translation: "Pharmacy" },
  { word: "Havaalanı", translation: "Airport" },
  { word: "Otobüs", translation: "Bus" },
  { word: "Taksi", translation: "Taxi" },
  { word: "Tren", translation: "Train" },
  { word: "Bilet", translation: "Ticket" },
  { word: "Şehir", translation: "City" },
  { word: "Köy", translation: "Village" },
  { word: "Ev", translation: "House" },
  { word: "Apartman", translation: "Apartment" },
  { word: "Okul", translation: "School" },
  { word: "Üniversite", translation: "University" },
  { word: "Öğretmen", translation: "Teacher" },
  { word: "Öğrenci", translation: "Student" },
  { word: "Ders", translation: "Lesson" },
  { word: "Kitap", translation: "Book" },
  { word: "Defter", translation: "Notebook" },
  { word: "Kalem", translation: "Pen" },
  { word: "Saat", translation: "Clock" },
  { word: "Dakika", translation: "Minute" },
  { word: "Saniye", translation: "Second" },
  { word: "Bugün", translation: "Today" },
  { word: "Dün", translation: "Yesterday" },
  { word: "Yarın", translation: "Tomorrow" },
  { word: "Sabah", translation: "Morning" },
  { word: "Öğle", translation: "Noon" },
  { word: "Akşam", translation: "Evening" },
  { word: "Gece", translation: "Night" },
  { word: "Pazartesi", translation: "Monday" },
  { word: "Salı", translation: "Tuesday" },
  { word: "Çarşamba", translation: "Wednesday" },
  { word: "Perşembe", translation: "Thursday" },
  { word: "Cuma", translation: "Friday" },
  { word: "Cumartesi", translation: "Saturday" },
  { word: "Pazar", translation: "Sunday" },
  { word: "Elma", translation: "Apple" },
  { word: "Armut", translation: "Pear" },
  { word: "Muz", translation: "Banana" },
  { word: "Portakal", translation: "Orange" },
  { word: "Çilek", translation: "Strawberry" },
  { word: "Karpuz", translation: "Watermelon" },
  { word: "Üzüm", translation: "Grapes" },
  { word: "Nar", translation: "Pomegranate" },
  { word: "Kavun", translation: "Melon" },
  { word: "Şeftali", translation: "Peach" },
  { word: "Kayısı", translation: "Apricot" },
  { word: "Erik", translation: "Plum" },
  { word: "Vişne", translation: "Sour cherry" },
  { word: "Kiraz", translation: "Cherry" },
  { word: "Havuç", translation: "Carrot" },
  { word: "Soğan", translation: "Onion" },
  { word: "Sarımsak", translation: "Garlic" },
  { word: "Patates", translation: "Potato" },
  { word: "Domates", translation: "Tomato" },
  { word: "Salatalık", translation: "Cucumber" },
  { word: "Biber", translation: "Pepper" },
  { word: "Ispanak", translation: "Spinach" },
  { word: "Lahana", translation: "Cabbage" },
  { word: "Marul", translation: "Lettuce" },
  { word: "Pırasa", translation: "Leek" },
  { word: "Brokoli", translation: "Broccoli" },
  { word: "Karnabahar", translation: "Cauliflower" },
  { word: "Mantar", translation: "Mushroom" },
  { word: "Bezelye", translation: "Pea" },
  { word: "Fasulye", translation: "Bean" },
  { word: "Mercimek", translation: "Lentil" },
  { word: "Nohut", translation: "Chickpea" },
  { word: "Badem", translation: "Almond" },
  { word: "Fındık", translation: "Hazelnut" },
  { word: "Ceviz", translation: "Walnut" },
  { word: "Fıstık", translation: "Peanut" },
  { word: "Susam", translation: "Sesame" },
  { word: "Hindistan cevizi", translation: "Coconut" },
  { word: "Zeytin", translation: "Olive" },
  { word: "Bal", translation: "Honey" },
  { word: "Reçel", translation: "Jam" },
  { word: "Tereyağı", translation: "Butter" },
  { word: "Peynir", translation: "Cheese" },
  { word: "Yoğurt", translation: "Yogurt" },
  { word: "Süt", translation: "Milk" },
  { word: "Yumurta", translation: "Egg" },
  { word: "Ekmek", translation: "Bread" },
  { word: "Makarna", translation: "Pasta" },
  { word: "Pilav", translation: "Rice" },
  { word: "Çorba", translation: "Soup" },
  { word: "Köfte", translation: "Meatball" },
  { word: "Balık", translation: "Fish" },
  { word: "Tavuk", translation: "Chicken" },
  { word: "Et", translation: "Meat" },
  { word: "Kuzu", translation: "Lamb" },
  { word: "Dana", translation: "Beef" },
  { word: "Sucuk", translation: "Sausage" },
  { word: "Pastırma", translation: "Cured meat" },
  { word: "Salam", translation: "Salami" },
  { word: "Sosis", translation: "Sausage" },
  { word: "Tuz", translation: "Salt" },
  { word: "Şeker", translation: "Sugar" },
  { word: "Biber", translation: "Pepper" },
  { word: "Sirke", translation: "Vinegar" },
  { word: "Zeytinyağı", translation: "Olive oil" },
  { word: "Ayçiçek yağı", translation: "Sunflower oil" },
  { word: "Ketçap", translation: "Ketchup" },
  { word: "Mayonez", translation: "Mayonnaise" },
  { word: "Hardal", translation: "Mustard" },
  { word: "Soya sosu", translation: "Soy sauce" },
  { word: "Çay", translation: "Tea" },
  { word: "Kahve", translation: "Coffee" },
  { word: "Meyve suyu", translation: "Fruit juice" },
  { word: "Soda", translation: "Soda" },
  { word: "Kola", translation: "Cola" },
  { word: "Bira", translation: "Beer" },
  { word: "Şarap", translation: "Wine" },
  { word: "Rakı", translation: "Raki" },
  { word: "Limonata", translation: "Lemonade" },
  { word: "Gazoz", translation: "Soft drink" },
  { word: "Dondurma", translation: "Ice cream" },
  { word: "Tatlı", translation: "Dessert" },
  { word: "Pasta", translation: "Cake" },
  { word: "Kurabiye", translation: "Cookie" },
  { word: "Baklava", translation: "Baklava" },
  { word: "Kadayıf", translation: "Kadayıf" },
  { word: "Lokum", translation: "Turkish delight" },
  { word: "Helva", translation: "Halva" },
  { word: "Puding", translation: "Pudding" },
  { word: "Çikolata", translation: "Chocolate" },
  { word: "Kedi", translation: "Cat" },
  { word: "Köpek", translation: "Dog" },
  { word: "Kuş", translation: "Bird" },
  { word: "Balık", translation: "Fish" },
  { word: "At", translation: "Horse" },
  { word: "İnek", translation: "Cow" },
  { word: "Koyun", translation: "Sheep" },
  { word: "Keçi", translation: "Goat" },
  { word: "Tavuk", translation: "Chicken" },
  { word: "Horoz", translation: "Rooster" },
  { word: "Ördek", translation: "Duck" },
  { word: "Kaz", translation: "Goose" },
  { word: "Eşek", translation: "Donkey" },
  { word: "Fil", translation: "Elephant" },
  { word: "Aslan", translation: "Lion" },
  { word: "Kaplan", translation: "Tiger" },
  { word: "Leopar", translation: "Leopard" },
  { word: "Çita", translation: "Cheetah" },
  { word: "Ayı", translation: "Bear" },
  { word: "Kurt", translation: "Wolf" },
  { word: "Tilki", translation: "Fox" },
  { word: "Geyik", translation: "Deer" },
  { word: "Zürafa", translation: "Giraffe" },
  { word: "Maymun", translation: "Monkey" },
  { word: "Timsah", translation: "Crocodile" },
  { word: "Kaplumbağa", translation: "Turtle" },
  { word: "Yılan", translation: "Snake" },
  { word: "Kertenkele", translation: "Lizard" },
  { word: "Kurbağa", translation: "Frog" },
  { word: "Karınca", translation: "Ant" },
  { word: "Arı", translation: "Bee" },
  { word: "Kelebek", translation: "Butterfly" },
  { word: "Örümcek", translation: "Spider" },
  { word: "Sinek", translation: "Fly" },
  { word: "Böcek", translation: "Bug" },
  { word: "Akrep", translation: "Scorpion" },
  { word: "Denizanası", translation: "Jellyfish" },
  { word: "Ahtapot", translation: "Octopus" },
  { word: "Yengeç", translation: "Crab" },
  { word: "Istakoz", translation: "Lobster" },
  { word: "Deniz yıldızı", translation: "Starfish" },
  { word: "Balina", translation: "Whale" },
  { word: "Yunus", translation: "Dolphin" },
  { word: "Fok", translation: "Seal" },
  { word: "Penguen", translation: "Penguin" },
  { word: "Kartal", translation: "Eagle" },
  { word: "Şahin", translation: "Hawk" },
  { word: "Baykuş", translation: "Owl" },
  { word: "Karga", translation: "Crow" },
  { word: "Serçe", translation: "Sparrow" },
  { word: "Güvercin", translation: "Pigeon" },
  { word: "Papağan", translation: "Parrot" },
  { word: "Kumru", translation: "Dove" },
  { word: "Leylek", translation: "Stork" },
  { word: "Tavus kuşu", translation: "Peacock" },
  { word: "Hindi", translation: "Turkey" },
  { word: "Deve", translation: "Camel" },
  { word: "Su aygırı", translation: "Hippopotamus" },
  { word: "Gergedan", translation: "Rhinoceros" },
  { word: "Koala", translation: "Koala" },
  { word: "Kanguru", translation: "Kangaroo" },
  { word: "Panda", translation: "Panda" },
  { word: "Sincap", translation: "Squirrel" },
  { word: "Kirpi", translation: "Hedgehog" },
  { word: "Yarasa", translation: "Bat" },
  { word: "Kunduz", translation: "Beaver" },
  { word: "Fare", translation: "Mouse" },
  { word: "Sıçan", translation: "Rat" },
  { word: "Tavşan", translation: "Rabbit" },
  { word: "Dağ keçisi", translation: "Mountain goat" },
  { word: "Çakal", translation: "Jackal" },
  { word: "Sırtlan", translation: "Hyena" },
  { word: "Fok balığı", translation: "Seal" },
  { word: "Deniz aslanı", translation: "Sea lion" },
  { word: "Mors", translation: "Walrus" },
  { word: "Ağaç kurbağası", translation: "Tree frog" },
  { word: "Uğur böceği", translation: "Ladybug" },
  { word: "Kene", translation: "Tick" },
  { word: "Salyangoz", translation: "Snail" },
  { word: "Solucan", translation: "Worm" },
  { word: "Deniz kestanesi", translation: "Sea urchin" },
  { word: "Deniz atı", translation: "Seahorse" },
  { word: "Kerevit", translation: "Crayfish" },
  { word: "Tarantula", translation: "Tarantula" },
  { word: "Hamamböceği", translation: "Cockroach" },
  { word: "Gümüş balığı", translation: "Silverfish" },
  { word: "Kurtçuk", translation: "Maggot" },
  { word: "Ev", translation: "House" },
  { word: "Apartman", translation: "Apartment" },
  { word: "Bina", translation: "Building" },
  { word: "Bahçe", translation: "Garden" },
  { word: "Oda", translation: "Room" },
  { word: "Salon", translation: "Living room" },
  { word: "Mutfak", translation: "Kitchen" },
  { word: "Banyo", translation: "Bathroom" },
  { word: "Tuvalet", translation: "Toilet" },
  { word: "Yatak odası", translation: "Bedroom" },
  { word: "Koridor", translation: "Corridor" },
  { word: "Merdiven", translation: "Stairs" },
  { word: "Balkon", translation: "Balcony" },
  { word: "Çatı", translation: "Roof" },
  { word: "Kapı", translation: "Door" },
  { word: "Pencere", translation: "Window" },
  { word: "Duvar", translation: "Wall" },
  { word: "Tavan", translation: "Ceiling" },
  { word: "Zemin", translation: "Floor" },
  { word: "Halı", translation: "Carpet" },
  { word: "Perde", translation: "Curtain" },
  { word: "Lamba", translation: "Lamp" },
  { word: "Sandalye", translation: "Chair" },
  { word: "Masa", translation: "Table" },
  { word: "Dolap", translation: "Closet" },
  { word: "Koltuk", translation: "Armchair" },
  { word: "Kanepe", translation: "Sofa" },
  { word: "Televizyon", translation: "Television" },
  { word: "Buzdolabı", translation: "Refrigerator" },
  { word: "Fırın", translation: "Oven" },
  { word: "Çamaşır makinesi", translation: "Washing machine" },
  { word: "Bulaşık makinesi", translation: "Dishwasher" },
  { word: "Çekmece", translation: "Drawer" },
  { word: "Saat", translation: "Clock" },
  { word: "Ayna", translation: "Mirror" },
  { word: "Şemsiye", translation: "Umbrella" },
  { word: "Bilgisayar", translation: "Computer" },
  { word: "Telefon", translation: "Phone" },
  { word: "Radyo", translation: "Radio" },
  { word: "Klavye", translation: "Keyboard" },
  { word: "Fare", translation: "Mouse (computer)" },
  { word: "Kitap", translation: "Book" },
  { word: "Gazete", translation: "Newspaper" },
  { word: "Dergi", translation: "Magazine" },
  { word: "Defter", translation: "Notebook" },
  { word: "Kalem", translation: "Pen" },
  { word: "Kurşun kalem", translation: "Pencil" },
  { word: "Silgi", translation: "Eraser" },
  { word: "Cetvel", translation: "Ruler" },
  { word: "Makas", translation: "Scissors" },
  { word: "Zımba", translation: "Stapler" },
  { word: "Ataç", translation: "Paperclip" },
  { word: "Bant", translation: "Tape" },
  { word: "Poşet", translation: "Plastic bag" },
  { word: "Çanta", translation: "Bag" },
  { word: "Cüzdan", translation: "Wallet" },
  { word: "Anahtar", translation: "Key" },
  { word: "Kapı kilidi", translation: "Door lock" },
  { word: "Ceket", translation: "Jacket" },
  { word: "Mont", translation: "Coat" },
  { word: "Pantolon", translation: "Pants" },
  { word: "Gömlek", translation: "Shirt" },
  { word: "Bluz", translation: "Blouse" },
  { word: "Etek", translation: "Skirt" },
  { word: "Elbise", translation: "Dress" },
  { word: "Kravat", translation: "Tie" },
  { word: "Çorap", translation: "Socks" },
  { word: "Ayakkabı", translation: "Shoes" },
  { word: "Bot", translation: "Boots" },
  { word: "Terlik", translation: "Slippers" },
  { word: "Şapka", translation: "Hat" },
  { word: "Eldiven", translation: "Gloves" },
  { word: "Atkı", translation: "Scarf" },
  { word: "Gözlük", translation: "Glasses" },
  { word: "Saat", translation: "Watch" },
  { word: "Yüzük", translation: "Ring" },
  { word: "Bilezik", translation: "Bracelet" },
  { word: "Kolye", translation: "Necklace" },
  { word: "Küpe", translation: "Earrings" },
  { word: "Parfüm", translation: "Perfume" },
  { word: "Sabun", translation: "Soap" },
  { word: "Şampuan", translation: "Shampoo" },
  { word: "Diş fırçası", translation: "Toothbrush" },
  { word: "Diş macunu", translation: "Toothpaste" },
  { word: "Havlu", translation: "Towel" },
  { word: "Tarak", translation: "Comb" },
  { word: "Fırça", translation: "Brush" },
  { word: "Masa", translation: "Table" },
  { word: "Sandalye", translation: "Chair" },
  { word: "Halı", translation: "Carpet" },
  { word: "Perde", translation: "Curtain" },
  { word: "Lamba", translation: "Lamp" },
  { word: "Yatak", translation: "Bed" },
  { word: "Battaniye", translation: "Blanket" },
  { word: "Yastık", translation: "Pillow" },
  { word: "Nevresim", translation: "Bed sheet" },
  { word: "Dolap", translation: "Closet" },
  { word: "Çekmece", translation: "Drawer" },
  { word: "Televizyon", translation: "Television" },
  { word: "Kumanda", translation: "Remote control" },
  { word: "Buzdolabı", translation: "Refrigerator" },
  { word: "Fırın", translation: "Oven" },
  { word: "Çamaşır makinesi", translation: "Washing machine" },
  { word: "Bulaşık makinesi", translation: "Dishwasher" },
  { word: "Mikrodalga", translation: "Microwave" },
  { word: "Tost makinesi", translation: "Toaster" },
  { word: "Su ısıtıcısı", translation: "Kettle" },
  { word: "Çaydanlık", translation: "Teapot" },
  { word: "Tava", translation: "Pan" },
  { word: "Tencere", translation: "Pot" },
  { word: "Kepçe", translation: "Ladle" },
  { word: "Kaşık", translation: "Spoon" },
  { word: "Çatal", translation: "Fork" },
  { word: "Bıçak", translation: "Knife" },
  { word: "Tabak", translation: "Plate" },
  { word: "Bardak", translation: "Glass" },
  { word: "Fincan", translation: "Cup" },
  { word: "Şişe", translation: "Bottle" },
  { word: "Kavanoz", translation: "Jar" },
  { word: "Çöp", translation: "Garbage" },
  { word: "Çöp kutusu", translation: "Trash bin" },
  { word: "Deterjan", translation: "Detergent" },
  { word: "Sabun", translation: "Soap" },
  { word: "Şampuan", translation: "Shampoo" },
  { word: "Diş macunu", translation: "Toothpaste" },
  { word: "Diş fırçası", translation: "Toothbrush" },
  { word: "Havlu", translation: "Towel" },
  { word: "Tarak", translation: "Comb" },
  { word: "Fırça", translation: "Brush" },
  { word: "Parfüm", translation: "Perfume" },
  { word: "Deodorant", translation: "Deodorant" },
  { word: "Ayna", translation: "Mirror" },
  { word: "Saat", translation: "Clock" },
  { word: "Takvim", translation: "Calendar" },
  { word: "Harita", translation: "Map" },
  { word: "Anahtar", translation: "Key" },
  { word: "Çanta", translation: "Bag" },
  { word: "Cüzdan", translation: "Wallet" },
  { word: "Şemsiye", translation: "Umbrella" },
  { word: "Gözlük", translation: "Glasses" },
  { word: "Güneş gözlüğü", translation: "Sunglasses" },
  { word: "El feneri", translation: "Flashlight" },
  { word: "Pil", translation: "Battery" },
  { word: "Kablo", translation: "Cable" },
  { word: "Priz", translation: "Socket" },
  { word: "Fiş", translation: "Plug" },
  { word: "Uzatma kablosu", translation: "Extension cord" },
  { word: "Telefon", translation: "Phone" },
  { word: "Bilgisayar", translation: "Computer" },
  { word: "Tablet", translation: "Tablet" },
  { word: "Kulaklık", translation: "Headphones" },
  { word: "Hoparlör", translation: "Speaker" },
  { word: "Mikrofon", translation: "Microphone" },
  { word: "Yazıcı", translation: "Printer" },
  { word: "Klavye", translation: "Keyboard" },
  { word: "Fare", translation: "Mouse" },
  { word: "Monitör", translation: "Monitor" },
  { word: "Televizyon", translation: "TV" },
  { word: "Radyo", translation: "Radio" },
  { word: "Oyun konsolu", translation: "Game console" },
  { word: "Joystick", translation: "Joystick" },
  { word: "DVD oynatıcı", translation: "DVD player" },
  { word: "Kamera", translation: "Camera" },
  { word: "Fotoğraf makinesi", translation: "Photographic camera" },
  { word: "Müzik", translation: "Music" },
  { word: "Şarkı", translation: "Song" },
  { word: "Enstrüman", translation: "Instrument" },
  { word: "Gitar", translation: "Guitar" },
  { word: "Piyano", translation: "Piano" },
  { word: "Keman", translation: "Violin" },
  { word: "Davul", translation: "Drum" },
  { word: "Flüt", translation: "Flute" },
  { word: "Saksafon", translation: "Saxophone" },
  { word: "Trompet", translation: "Trumpet" },
  { word: "Mikrofon", translation: "Microphone" },
  { word: "Konser", translation: "Concert" },
  { word: "Orkestra", translation: "Orchestra" },
  { word: "Koro", translation: "Choir" },
  { word: "Melodi", translation: "Melody" },
  { word: "Ritim", translation: "Rhythm" },
  { word: "Nota", translation: "Note" },
  { word: "Şiir", translation: "Poem" },
  { word: "Roman", translation: "Novel" },
  { word: "Hikaye", translation: "Story" },
  { word: "Gazete", translation: "Newspaper" },
  { word: "Dergi", translation: "Magazine" },
  { word: "Makale", translation: "Article" },
  { word: "Kitap", translation: "Book" },
  { word: "Yazar", translation: "Writer" },
  { word: "Şair", translation: "Poet" },
  { word: "Ressam", translation: "Painter" },
  { word: "Heykel", translation: "Sculpture" },
  { word: "Sanat", translation: "Art" },
  { word: "Müze", translation: "Museum" },
  { word: "Tiyatro", translation: "Theater" },
  { word: "Sinema", translation: "Cinema" },
  { word: "Film", translation: "Movie" },
  { word: "Dizi", translation: "TV Series" },
  { word: "Oyuncu", translation: "Actor" },
  { word: "Sahne", translation: "Stage" },
  { word: "Perde", translation: "Curtain" },
  { word: "Replik", translation: "Line" },
  { word: "Senaryo", translation: "Script" },
  { word: "Kostüm", translation: "Costume" },
  { word: "Dekor", translation: "Decoration" },
  { word: "Efekt", translation: "Effect" },
  { word: "Afiş", translation: "Poster" },
  { word: "Yönetmen", translation: "Director" },
  { word: "Prodüktör", translation: "Producer" },
  { word: "Stüdyo", translation: "Studio" },
  { word: "Kamera", translation: "Camera" },
  { word: "Sahne", translation: "Scene" },
  { word: "Film müziği", translation: "Soundtrack" },
  { word: "Belgesel", translation: "Documentary" },
  { word: "Animasyon", translation: "Animation" },
  { word: "Komedi", translation: "Comedy" },
  { word: "Dram", translation: "Drama" },
  { word: "Aksiyon", translation: "Action" },
  { word: "Macera", translation: "Adventure" },
  { word: "Gerilim", translation: "Thriller" },
  { word: "Korku", translation: "Horror" },
  { word: "Bilim kurgu", translation: "Science fiction" },
  { word: "Fantastik", translation: "Fantasy" },
  { word: "Romantik", translation: "Romantic" },
  { word: "Polisiye", translation: "Detective" },
  { word: "Savaş", translation: "War" },
  { word: "Tarih", translation: "History" },
  { word: "Biyografi", translation: "Biography" },
  { word: "Spor", translation: "Sport" },
  { word: "Futbol", translation: "Football" },
  { word: "Basketbol", translation: "Basketball" },
  { word: "Voleybol", translation: "Volleyball" },
  { word: "Tenis", translation: "Tennis" },
  { word: "Golf", translation: "Golf" },
  { word: "Boks", translation: "Boxing" },
  { word: "Masa tenisi", translation: "Table tennis" },
  { word: "Atletizm", translation: "Athletics" },
  { word: "Güreş", translation: "Wrestling" },
  { word: "Yüzme", translation: "Swimming" },
  { word: "Kayak", translation: "Skiing" },
  { word: "Dalış", translation: "Diving" },
  { word: "Motor sporları", translation: "Motor sports" },
  { word: "Bisiklet", translation: "Cycling" },
  { word: "Maraton", translation: "Marathon" },
  { word: "Jimnastik", translation: "Gymnastics" },
  { word: "Müzik", translation: "Music" },
  { word: "Şarkı", translation: "Song" },
  { word: "Enstrüman", translation: "Instrument" },
  { word: "Gitar", translation: "Guitar" },
  { word: "Piyano", translation: "Piano" },
  { word: "Keman", translation: "Violin" },
  { word: "Davul", translation: "Drum" },
  { word: "Flüt", translation: "Flute" },
  { word: "Saksafon", translation: "Saxophone" },
  { word: "Trompet", translation: "Trumpet" },
  { word: "Mikrofon", translation: "Microphone" },
  { word: "Konser", translation: "Concert" },
  { word: "Orkestra", translation: "Orchestra" },
  { word: "Koro", translation: "Choir" },
  { word: "Melodi", translation: "Melody" },
  { word: "Ritim", translation: "Rhythm" },
  { word: "Nota", translation: "Note" },
  { word: "Şiir", translation: "Poem" },
  { word: "Roman", translation: "Novel" },
  { word: "Hikaye", translation: "Story" },
  { word: "Gazete", translation: "Newspaper" },
  { word: "Dergi", translation: "Magazine" },
  { word: "Makale", translation: "Article" },
  { word: "Kitap", translation: "Book" },
  { word: "Yazar", translation: "Writer" },
  { word: "Şair", translation: "Poet" },
  { word: "Ressam", translation: "Painter" },
  { word: "Heykel", translation: "Sculpture" },
  { word: "Sanat", translation: "Art" },
  { word: "Müze", translation: "Museum" },
  { word: "Tiyatro", translation: "Theater" },
  { word: "Sinema", translation: "Cinema" },
  { word: "Film", translation: "Movie" },
  { word: "Dizi", translation: "TV Series" },
  { word: "Oyuncu", translation: "Actor" },
  { word: "Sahne", translation: "Stage" },
  { word: "Perde", translation: "Curtain" },
  { word: "Replik", translation: "Line" },
  { word: "Senaryo", translation: "Script" },
  { word: "Kostüm", translation: "Costume" },
  { word: "Dekor", translation: "Decoration" },
  { word: "Efekt", translation: "Effect" },
  { word: "Afiş", translation: "Poster" },
  { word: "Yönetmen", translation: "Director" },
  { word: "Prodüktör", translation: "Producer" },
  { word: "Stüdyo", translation: "Studio" },
  { word: "Kamera", translation: "Camera" },
  { word: "Sahne", translation: "Scene" },
  { word: "Film müziği", translation: "Soundtrack" },
  { word: "Belgesel", translation: "Documentary" },
  { word: "Animasyon", translation: "Animation" },
  { word: "Komedi", translation: "Comedy" },
  { word: "Dram", translation: "Drama" },
  { word: "Aksiyon", translation: "Action" },
  { word: "Macera", translation: "Adventure" },
  { word: "Gerilim", translation: "Thriller" },
  { word: "Korku", translation: "Horror" },
  { word: "Bilim kurgu", translation: "Science fiction" },
  { word: "Fantastik", translation: "Fantasy" },
  { word: "Romantik", translation: "Romantic" },
  { word: "Polisiye", translation: "Detective" },
  { word: "Savaş", translation: "War" },
  { word: "Tarih", translation: "History" },
  { word: "Biyografi", translation: "Biography" },
  { word: "Spor", translation: "Sport" },
  { word: "Futbol", translation: "Football" },
  { word: "Basketbol", translation: "Basketball" },
  { word: "Voleybol", translation: "Volleyball" },
  { word: "Tenis", translation: "Tennis" },
  { word: "Golf", translation: "Golf" },
  { word: "Boks", translation: "Boxing" },
  { word: "Masa tenisi", translation: "Table tennis" },
  { word: "Atletizm", translation: "Athletics" },
  { word: "Güreş", translation: "Wrestling" },
  { word: "Yüzme", translation: "Swimming" },
  { word: "Kayak", translation: "Skiing" },
  { word: "Dalış", translation: "Diving" },
  { word: "Motor sporları", translation: "Motor sports" },
  { word: "Bisiklet", translation: "Cycling" },
  { word: "Maraton", translation: "Marathon" },
  { word: "Jimnastik", translation: "Gymnastics" },
  { word: "Eskrim", translation: "Fencing" },
  { word: "Ragbi", translation: "Rugby" },
  { word: "Hentbol", translation: "Handball" },
  { word: "Kriket", translation: "Cricket" },
  { word: "Okçuluk", translation: "Archery" },
  { word: "Binicilik", translation: "Equestrian" },
  { word: "Yelkencilik", translation: "Sailing" },
  { word: "Su topu", translation: "Water polo" },
];
